.PHONY: seed start opt route migrate

migrate:
	php artisan migrate:fresh

seed:
	php artisan migrate:fresh --seed

route:
	php artisan route:list

start:
	php artisan serve

opt:
	php artisan optimize